version: "3.9"

services:
    pkg:
        build: .
        ports:
            - "6001:6001"
        depends_on:
            - db
    db:
        image: "mysql:latest"
        volumes:
          - sqlvolume:/var/opt/mysql

        environment:
            MYSQL_ROOT_PASSWORD: "9XXf@2jnSOCA"
            MYSQL_DATABASE: "qb_user_db"
        ports:
            - "3306:3306"

volumes:
  sqlvolume: