version: '3.9'

services:
    userservice:
        build:
            context: .
            dockerfile: Dockerfile.local
        container_name: userservice
        ports:
            - "0.0.0.0:6001:6001"
        depends_on:
            - db
        networks:
            - qbreak-network
    db:
        image: "mcr.microsoft.com/mssql/server"
        container_name: userdb
        volumes:
          - user_volume:/var/opt/mssql/
        environment:
            SA_PASSWORD: "HW5etW#4iyWCNu"
            ACCEPT_EULA: "Y"
        ports:
            - "0.0.0.0:1532:1433"
        networks:
            - qbreak-network

volumes:
  user_volume:

networks:
    qbreak-network:
        external: true